### PR TITLE
19.03.2021

### PR DESCRIPTION
**Pull request by oliverstotz**
hi, lucas !

i hope i did everything right ;-)

### CODE REVIEW

**Comment by Lucarda** [comment]
Looks like you deleted all the "modified by jyg on 14.02.19" parts.

Can you insert them back?

**Comment by Lucarda** [comment]
> Looks like you deleted all the "modified by jyg on 14.02.19" parts.

I mean in the `dnd-plugin.tcl` file

**Comment by oliverstotz** [comment]
hi, just put them back. i hope this is what you meant.
basically it adds another message to the "dnd-dropped" receiver with the mouse position and a "done" bang

**Comment by Lucarda** [comment]
Ok that seems good. I'll be testing in depth later before merging.

Also can you change `tkdnd/pkgIndex.tcl` back to the original.

**Comment by Lucarda** [comment]
Ok, don't mind about `tkdnd/pkgIndex.tcl` i'll fix that later.

:)

**Pull request merged**
